# Site settings
baseurl: ''
url: 'http://ember-cli.com'

# Build settings
markdown: kramdown
highlighter: pygments
exclude: ['node_modules', 'vendor']

# TODO: Automate version bump on release
version: 2.2.0-beta.3

gems:
  - jekyll-feed
  - github-pages
